[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    smoke: Smoke Tests
    regression: Regression Tests
    integration: Integration Tests
    validation: Valid Scenarios
# Method A: Set a default browser flag using addopts
addopts = --browser chromium

# Method B: Define custom variables for your test suite to parse
[drivers]
supported_browsers = chrome firefox edge